language: python
cache:
    - apt
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install fglrx opencl-headers
python:
    - "2.7"
    - "3.3"
env:
    - PIP_SPECIFIER=.
    - PIP_SPECIFIER=.[opencl]
install:
    - pip install numpy
    - pip install -e $PIP_SPECIFIER
script:
    - python setup.py nosetests
    - python scripts/benchmark_opencl.py

