language: python
cache:
    - apt
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install fglrx opencl-headers
python:
    - "2.7"
    - "3.3"
env:
    - PIP_SPECIFIER=.[docs]
    - PIP_SPECIFIER=.[opencl,docs]
install:
    - pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
    - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors numpy coveralls
    - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors -e $PIP_SPECIFIER
script:
    - python setup.py nosetests
    - python scripts/benchmark_opencl.py
    - python setup.py build_sphinx
after_success:
    - coveralls

